# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a3bad228bca0fa344c1845ca32b3b7fb98f682e08c19953c02f36eaf0240844a4065108099454539e3c5f7ed6d0e377ca8479a6de5c5d65588ef73e86be86bb

test:
  secret_key_base: 35c909fc093c43416b27e82f28ebc372d9af198851323c3caf6ffd3d9aa6962bc07d6460cd74970e8ab7eda657930650ff78bd0306a5763cb650549149a0bcd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
